name: non_uniform_border
description: Provides a border class for Flutter that allows different widths for each side with a single color.
version: 1.0.0
homepage: https://github.com/bernaferrari/non_uniform_border

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
